
describe('AC-XX- As a user, I need, So that.', () => {
  it('Scenario 1 - Zoom in to the max and the Zoom in button is disabled', () => {
    cy.visit('http://localhost:3000/planning.html')
    cy.wait(2500)
    cy.get('.fm-c-zoom > :nth-child(1) > .fm-c-btn').click()
    cy.wait(2500)
    cy.get('.fm-c-zoom > :nth-child(1) > .fm-c-btn').click()
    cy.wait(2500)
    cy.get('.fm-c-zoom > :nth-child(1) > .fm-c-btn').click()
    cy.wait(2500)
    cy.get('.fm-c-zoom > :nth-child(1) > .fm-c-btn').click()
    cy.wait(2500)
    cy.get('.fm-c-zoom > :nth-child(1) > .fm-c-btn').click()
    cy.wait(2500)
    cy.url().should('include', '/planning.html?cz=324973,536891,20')
    cy.compareSnapshot(Cypress.env('tags') + 'Zoom in Evidence')
  })
    it('Scenario 1 - Zoom in to the max and the Zoom in button is disabled', () => {
      cy.visit('http://localhost:3000/planning.html')
      cy.wait(2000)
      cy.get('.fm-c-zoom > :nth-child(1) > .fm-c-btn').click()
      cy.wait(2500)
      cy.get('.fm-c-zoom > :nth-child(1) > .fm-c-btn').click()
      cy.wait(2500)
      cy.get('.fm-c-zoom > :nth-child(1) > .fm-c-btn').click()
      cy.wait(2500)
      cy.get('.fm-c-zoom > :nth-child(1) > .fm-c-btn').click()
      cy.wait(2500)
      cy.get('.fm-c-zoom > :nth-child(1) > .fm-c-btn').click()
      cy.wait(2500)
      cy.url().should('include', '/planning.html?cz=324973,536891,20')
      cy.compareSnapshot(Cypress.env('tags') + 'Zoom in Evidence')
    })
   it('Scenario 2 - Zoom out to the max and the Zoom out button is disabled', () => {
        cy.visit('http://localhost:3000/planning.html')
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.url().should('include', '/planning.html?cz=324973,536891,7')
        cy.compareSnapshot(Cypress.env('tags') + 'Zoom out Evidence')
      })
      it('Scenario 3 - Zoom out to the max and the Zoom out button is disabled', () => {
        cy.viewport('iphone-6') 
        cy.visit('http://localhost:3000/planning.html?cz=324973,536891,7')
        cy.wait(5000)
        cy.url().should('include', '/planning.html?cz=324973,536891,7')
        cy.compareSnapshot(Cypress.env('tags') + 'Mobile iphone-6 Zoom out Evidence')
      })
      it('Scenario 4 - Zoom out to the max and the Zoom out button is disabled', () => {
        cy.viewport('ipad-2') 
        cy.visit('http://localhost:3000/planning.html')
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(2) > .fm-c-btn').click()
        cy.wait(2000)
        cy.url().should('include', '/planning.html?cz=324973,536891,7')
        cy.compareSnapshot(Cypress.env('tags') + 'Tablet Zoom out Evidence')
      })
      it('Scenario 5 - Zoom in to the max and the Zoom in button is disabled', () => {
        cy.viewport('ipad-2') 
        cy.visit('http://localhost:3000/planning.html')
        cy.wait(2000)
        cy.get('.fm-c-zoom > :nth-child(1) > .fm-c-btn').click()
        cy.wait(2500)
        cy.get('.fm-c-zoom > :nth-child(1) > .fm-c-btn').click()
        cy.wait(2500)
        cy.get('.fm-c-zoom > :nth-child(1) > .fm-c-btn').click()
        cy.wait(2500)
        cy.get('.fm-c-zoom > :nth-child(1) > .fm-c-btn').click()
        cy.wait(2500)
        cy.get('.fm-c-zoom > :nth-child(1) > .fm-c-btn').click()
        cy.wait(2500)
        cy.url().should('include', '/planning.html?cz=324973,536891,20')
        cy.compareSnapshot(Cypress.env('tags') + 'Tablets Zoom in Evidence')
      })
      

})