name: "PR Base Branch Check"

on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  check-base-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check valid base branch
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
          echo "Attempting to merge ${SOURCE_BRANCH} into ${BASE_BRANCH}"
          if [ "$BASE_BRANCH" = "main" ]; then
            echo base is main
            if [ "$SOURCE_BRANCH" != "development" ]; then
              echo "Source branch is not 'development', so cannot be merged to main."
              exit 1
            fi
          fi
          echo "Branches ok to be merged"
