name: Sync development with main
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Reset development to match main
        run: |
          git fetch origin
          git checkout development
          git reset --hard origin/main
          git push --force origin development
