name: Sync development with main

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'development'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 20  # Fetch enough history to check for recent reverts

      - name: Check for Recent Revert in Main
        run: |
          if git log -20 --pretty=%s | grep -i "Revert"; then
            echo "Recent revert found in main. Aborting Auto PR."
            exit 1
          fi

      - name: Authenticate with GitHub (Using GITHUB_TOKEN)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        run: |
          gh pr create \
            --base development \
            --head main \
            --title "Sync main into development" \
            --body "Auto PR to sync main into development. No manual merge required if auto-merge is enabled."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
