name: Sync development with main

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'development'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10  # Fetch enough history for PR creation

      - name: Authenticate with GitHub (Using GITHUB_TOKEN)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        run: |
          gh pr create \
            --base development \
            --head main \
            --title "Sync main into development" \
            --body "Auto PR to sync main into development. No manual merge required if auto-merge is enabled."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
